baseURL = "http://codatest.netlify.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Coda Mix"
[markup.goldmark.renderer]
unsafe = true
